stages:
  - build
  - deploy

variables:
  AIRFLOW_IMAGE: $CI_REGISTRY_IMAGE/airflow:v1
  STREAMLIT_IMAGE: $CI_REGISTRY_IMAGE/streamlit:v1

build_job:
  stage: build
  tags: 
    - local-server

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $AIRFLOW_IMAGE -f Dockerfile.airflow .
    - docker build -t $STREAMLIT_IMAGE -f Dockerfile .
    - docker push $AIRFLOW_IMAGE
    - docker push $STREAMLIT_IMAGE

deploy_job:
  stage: deploy
  tags:
    - local-server  
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    - rm -f .env

    - echo "DB_NAME=$DB_NAME" > .env
    - echo "DB_USER=$DB_USER" >> .env
    - echo "DB_PASSWORD=$DB_PASSWORD" >> .env
    - echo "DB_HOST=$DB_HOST" >> .env
    - echo "DB_PORT=$DB_PORT" >> .env
    - echo "NEWS_API_KEY=$NEWS_API_KEY" >> .env
    - echo "_PIP_ADDITIONAL_REQUIREMENTS=$_PIP_ADDITIONAL_REQUIREMENTS" >> .env
    - echo "AIRFLOW_ADMIN_USER=$AIRFLOW_ADMIN_USER" >> .env
    - echo "AIRFLOW_ADMIN_PASSWORD=$AIRFLOW_ADMIN_PASSWORD" >> .env

    - ls -la .env
    
    - docker-compose pull
    - docker-compose up -d